# Generated by Django 2.2.5 on 2021-06-19 22:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TravelsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 19, 22, 22, 2, 776019, tzinfo=utc)),
        ),
    ]
