# Generated by Django 2.2.5 on 2021-06-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelsApp', '0005_event_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='dogsAllowed',
        ),
        migrations.RemoveField(
            model_name='event',
            name='kidsAllowed',
        ),
        migrations.AddField(
            model_name='activity',
            name='dogsAllowed',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='kidsAllowed',
            field=models.BooleanField(default=0),
        ),
    ]
