# Generated by Django 2.2.5 on 2021-07-14 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TravelsApp', '0010_auto_20210714_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='surname',
        ),
    ]
