# Generated by Django 2.2.5 on 2021-07-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelsApp', '0011_auto_20210714_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='user_type',
            field=models.CharField(choices=[('Std', 'Standard'), ('Amb', 'Ambassador'), ('Lead', 'Leader'), ('Emp', 'Employee')], default='Std', max_length=4),
        ),
    ]
