# Generated by Django 2.2.5 on 2021-07-19 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TravelsApp', '0014_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='subscription_exp_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
