# Generated by Django 2.2.5 on 2021-07-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelsApp', '0016_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='desctiption',
            field=models.CharField(default='Description', max_length=128),
            preserve_default=False,
        ),
    ]
