# Generated by Django 2.2.5 on 2021-07-20 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TravelsApp', '0017_setting_desctiption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='desctiption',
            new_name='description',
        ),
    ]
