# Generated by Django 2.2.5 on 2021-07-26 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TravelsApp', '0020_remove_userprofileinfo_subscription_exp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='queued_partecipants',
            field=models.ManyToManyField(related_name='my_queued_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
