# Generated by Django 2.2.5 on 2021-08-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelsApp', '0024_order_payment_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='credits_to_use',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
