# Generated by Django 2.2.5 on 2021-08-13 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TravelsApp', '0027_auto_20210806_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TravelsApp.Event')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelsApp.Order')),
            ],
        ),
    ]
