# Generated by Django 2.2.5 on 2021-08-13 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TravelsApp', '0031_ticket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
    ]
