# Generated by Django 2.2.5 on 2021-06-19 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TravelsApp', '0003_auto_20210620_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
