# Generated by Django 2.2.5 on 2021-06-19 22:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TravelsApp', '0004_remove_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
