# Generated by Django 2.2.5 on 2021-06-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelsApp', '0006_auto_20210624_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='maxNumPartecipants',
        ),
        migrations.RemoveField(
            model_name='event',
            name='minNumPartecipants',
        ),
        migrations.AddField(
            model_name='activity',
            name='maxNumPartecipants',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='minNumPartecipants',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
