# Generated by Django 2.2.5 on 2021-07-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelsApp', '0009_auto_20210711_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='name',
            field=models.CharField(default='no_name_specified', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='surname',
            field=models.CharField(default='no_surname_specified', max_length=100),
            preserve_default=False,
        ),
    ]
