# Generated by Django 2.2.5 on 2021-07-20 22:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TravelsApp', '0018_auto_20210720_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='exp_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
