# Generated by Django 2.2.5 on 2021-07-20 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TravelsApp', '0019_userprofileinfo_exp_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='subscription_exp_date',
        ),
    ]
