# Generated by Django 2.2.5 on 2021-08-05 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TravelsApp', '0021_event_queued_partecipants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Chart', max_length=24)),
                ('items', models.CharField(default='', max_length=600)),
                ('total', models.FloatField(default=0)),
            ],
        ),
    ]
