# Generated by Django 2.2.5 on 2021-08-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelsApp', '0028_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='valid', max_length=30),
        ),
    ]
