# Generated by Django 2.2.5 on 2021-09-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelsApp', '0030_outmail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outmail',
            name='context',
        ),
        migrations.AddField(
            model_name='outmail',
            name='html',
            field=models.CharField(default='no value assigned', max_length=2048),
            preserve_default=False,
        ),
    ]
