# Generated by Django 2.2.5 on 2021-09-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TravelsApp', '0031_auto_20210911_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outmail',
            old_name='type',
            new_name='template',
        ),
    ]
