# Generated by Django 2.2.5 on 2021-09-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelsApp', '0032_auto_20210911_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='outmail',
            name='subject',
            field=models.CharField(default='hallo', max_length=64),
            preserve_default=False,
        ),
    ]
