# Generated by Django 2.2.5 on 2021-09-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelsApp', '0033_outmail_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(default='xyz', max_length=200),
        ),
    ]
