# Generated by Django 2.2.5 on 2021-09-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelsApp', '0034_auto_20210917_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='credits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
