# Generated by Django 2.2.5 on 2021-09-23 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelsApp', '0036_event_refund_limit_delta_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='queued_partecipants',
            field=models.ManyToManyField(blank=True, related_name='my_queued_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
