# Generated by Django 2.2.5 on 2021-10-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelsApp', '0038_auto_20211009_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(max_length=2048),
        ),
    ]
