# Generated by Django 2.2.5 on 2021-10-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelsApp', '0039_auto_20211009_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activityDetail',
            field=models.CharField(default='Andremo su per la collina e poi giu per la collina', max_length=2048),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(max_length=512),
        ),
    ]
