# Generated by Django 2.2.5 on 2022-04-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelsApp', '0041_auto_20211011_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='is_minor',
            field=models.BooleanField(default=False),
        ),
    ]
