# Generated by Django 2.2.5 on 2022-04-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelsApp', '0043_userprofileinfo_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='activation_code',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
